#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Process vis.mac (and draw geometry)
#
/control/execute vis.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "511 keV"  "/gun/energy 511 keV"
/gui/addButton gun "10 MeV"  "/gun/energy 10 MeV"
/gui/addButton gun "50 MeV"   "/gun/energy 50 MeV"
/gui/addButton gun "10 GeV"   "/gun/energy 10 GeV"
/gui/addButton gun "1 GeV"              "/gun/energy 1 GeV" 
/gui/addButton gun "10 GeV"             "/gun/energy 10 GeV"
/gui/addButton gun "100 GeV"            "/gun/energy 100 GeV"
/gui/addButton gun "1000 GeV"           "/gun/energy 1000 GeV"
/gui/addButton gun "10000 GeV"          "/gun/energy 10000 GeV"
/gui/addButton gun "100000 GeV"         "/gun/energy 100000 GeV"
/gui/addButton gun "1000000 GeV"        "/gun/energy 1000000 GeV"
/gui/addButton gun "10000000 GeV"       "/gun/energy 10000000 GeV"
/gui/addButton gun "100000000 GeV"      "/gun/energy 100000000 GeV"
/gui/addButton gun "1000000000 GeV"     "/gun/energy 1000000000 GeV"
/gui/addButton gun "10000000000 GeV"    "/gun/energy 10000000000 GeV"
/gui/addButton gun "100000000000 GeV"   "/gun/energy 100000000000 GeV"



/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "tau-"    "/gun/particle tau-"
/gui/addButton gun "mu-"     "/gun/particle mu-"
/gui/addButton gun "pi0"     "/gun/particle pi0"
/gui/addButton gun "pi+"     "/gun/particle pi+"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
#

