# shoot optical photons

/run/initialize
/gun/particle mu-
/gun/energy 10 GeV
#/analysis/setFileName testFile
#/analysis/h1/set 1 10 0 50000
#/analysis/h1/set 2 10 0 50000
#/analysis/h1/set 3 16 2 4.2 eV
#/analysis/h1/set 3 16 300 620 nm




/tracking/verbose 0
/tracking/storeTrajectory 0
/run/beamOn 2










#/run/initialize
#/gun/particle opticalphoton
#/gun/energy 7.07 eV
#/gun/position 0 0 75 m 
#/gun/direction 0 0 1
#/gun/polarization 0 1 0
#/tracking/verbose 1
#/run/beamOn 100

